"""initial

Revision ID: 3ed8edf2fd27
Revises: 5bf2f16dbb05
Create Date: 2023-05-16 13:05:02.262947

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '3ed8edf2fd27'
down_revision = '5bf2f16dbb05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
