"""initial

Revision ID: 5bf2f16dbb05
Revises: 14f995a135f0
Create Date: 2023-05-16 12:57:30.088073

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5bf2f16dbb05'
down_revision = '14f995a135f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
