"""initial

Revision ID: f9dd82329511
Revises: 3ed8edf2fd27
Create Date: 2023-05-16 13:51:36.852332

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'f9dd82329511'
down_revision = '3ed8edf2fd27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
